version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_GC_OPTS=-Dfile.encoding=UTF-8"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 9200:9200
    networks:
      - elk
    user: "1000:1000"
    volumes:
      - elk-search:/usr/share/elasticsearch/data
      - ./elasticsearch/ocr_product_keyword.json:/usr/share/elasticsearch/config/ocr_product_keyword.json
      - ./elasticsearch/init-elasticsearch.sh:/usr/share/elasticsearch/config/init-elasticsearch.sh

  logstash:
    build: ./logstash
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "JAVA_OPTS=-Dfile.encoding=UTF-8"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_ENABLE_XDB=true
    volumes:
      - oradata:/u01/app/oracle/oradata
    networks:
      - elk

volumes:
  elk-search:
    driver: local
  oradata:
    driver: local

networks:
  elk:
    driver: bridge
