version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_GC_OPTS=-Dfile.encoding=UTF-8"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./ocr_product_keyword_template.json:/usr/share/elasticsearch/config/ocr_product_keyword_template.json
      - ./init-elasticsearch.sh:/docker-entrypoint-initdb.d/init-elasticsearch.sh
    ports:
      - 9200:9200
    networks:
      - elk
    user: "1000:1000" # Add this line to run as a non-root user
    command: >
      sh -c "elasticsearch-plugin install analysis-nori && elasticsearch"

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "JAVA_OPTS=-Dfile.encoding=UTF-8"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
